### ISSUE TITLE
query ╥﹏╥...

### ISSUE THREAD

**Issue by jun0wanan** [chuachinhon/wav2vec2_transformers#1]
hi,

       Thank you for your work ! how to do that (make sure to downsample them to 16kHz)?

Best,
jun

**Comment by chuachinhon** [comment]
You can use any audio editing software to downsample then export. Audacity is one (free) option: https://www.audacityteam.org/

**Comment by jun0wanan** [comment]
> You can use any audio editing software to downsample then export. Audacity is one (free) option: https://www.audacityteam.org/

If I have wav files   ,how can I get the audio embedding using wav2vec ?~ hope to  get your help
