### ISSUE TITLE
translate() - does not translate whole document

### ISSUE THREAD

**Issue by jeesunkim** [chuachinhon/wav2vec2_transformers#2]
Thanks for the interesting tutorial.
The asr_transcript works fine - but the translate () code only produces a few lines of translation. Any ideas?
Thanks

**Comment by chuachinhon** [comment]
Can't tell without seeing what kind of text you are working on.
But I suspect it could be a punctuation issue as the translate function uses a sentence tokenizer.

So either you add a period at the end of each transcribed clip:
transcript += transcription.lower() + ". " 

Or you remove sent_tokenize() from the translate function.

I have a few more notebooks on translation here: https://github.com/chuachinhon/practical_nlp/tree/master/notebooks

Some of the code might need to be updated if you are using transformers >=3.1

**Comment by jeesunkim** [comment]
Thanks for your prompt reply.
I think that you are right regarding punctuation 
Do you mean remove sent_tokenize in this line?
batch = tokenizer_translate.prepare_seq2seq_batch(sent_tokenize(text), return_tensors="pt")
Again thanks
Edit - just checked I am using transformers version 4.4.0.dev0 - I guess that this is the issue.

**Comment by chuachinhon** [comment]
Yeah, that's the right line to remove sent_tokenize, to see if it resolves the issue.

but transformers 4.4 might have other changes I'm not aware of. see if reverting to 4.3 helps?

**Comment by jeesunkim** [comment]
I decided to include the transcript += transcription.lower() + ". " line in the asr_transcript function and keep the sent_tokenize bit.
Also used your clean_text function 
And so now it works. Great!

Now down to the sentiment analysis  (running this in python - function by function) and realised I hadn't installed the plotly package for
import plotly.graph_objects as go
and
import plotly.express as px

So while still in python did:
import subprocess
import sys
def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])
install('plotly')

It all work nicely and am looking at a great Sentiment Analysis plot.
Once again - thanks for an excellent tutorial!

**Comment by chuachinhon** [comment]
Glad it worked out.
